import { Artist, Artwork } from '../types/artwork';
import { Product } from '../types/product';
import { GiftOccasion, GiftConcept } from '../types/gift';

export const MOCK_ARTISTS: Artist[] = [
  {
    id: 'artist-1',
    name: 'Elena Rostova',
    handle: '@elena_botanical',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
    bio: 'Contemporary botanical painter capturing quiet flora and warm morning light.',
    story: 'Elena grew up in a coastal orchard town. Her oil paintings blend ethereal Scandinavian minimalism with vibrant Mediterranean botanical textures.',
    location: 'Stockholm, Sweden',
    socialLinks: { instagram: 'https://instagram.com', website: 'https://elena-art.example.com' },
    featuredArtworkIds: ['art-1', 'art-2', 'art-3'],
    totalArtworks: 14,
  },
  {
    id: 'artist-2',
    name: 'Kenji Takahashi',
    handle: '@kenji_zen_ink',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80',
    bio: 'Minimalist ink wash and modern geometric landscape artist.',
    story: 'Kenji explores the balance of space, silence, and architectural geometry. His work bridges traditional Sumi-e ink with contemporary digital minimalism.',
    location: 'Kyoto, Japan',
    socialLinks: { instagram: 'https://instagram.com' },
    featuredArtworkIds: ['art-4', 'art-5', 'art-6'],
    totalArtworks: 18,
  },
  {
    id: 'artist-3',
    name: 'Amara Vance',
    handle: '@amaravance_studio',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
    bio: 'Abstract expressionist celebrating vibrant terracotta and golden warmth.',
    story: 'Amara captures emotion through layered acrylics and gold leaf. Her abstract pieces radiate positivity and warm domestic harmony.',
    location: 'Montreal, Canada',
    socialLinks: { instagram: 'https://instagram.com', website: 'https://amara.example.com' },
    featuredArtworkIds: ['art-7', 'art-8', 'art-9'],
    totalArtworks: 11,
  },
  {
    id: 'artist-4',
    name: 'Mateo Morales',
    handle: '@mateo_ceramic_art',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
    bio: 'Ceramic sculptor turned digital surface print designer.',
    story: 'Drawing inspiration from ancient pottery patterns and modern architecture, Mateo crafts soothing organic motifs with earthy clay tones.',
    location: 'Oaxaca, Mexico',
    socialLinks: { instagram: 'https://instagram.com' },
    featuredArtworkIds: ['art-10', 'art-11'],
    totalArtworks: 9,
  },
  {
    id: 'artist-5',
    name: 'Sophie Laurent',
    handle: '@sophie_impressionist',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?auto=format&fit=crop&w=1200&q=80',
    bio: 'Impressionist pastel painter celebrating quiet gardens and twilight hues.',
    story: 'Sophie captures soft afternoon shadows, wild poppies, and serene garden ponds in luminous pastel tones that bring calm to any living space.',
    location: 'Provence, France',
    socialLinks: { instagram: 'https://instagram.com', website: 'https://sophie.example.com' },
    featuredArtworkIds: ['art-12', 'art-13'],
    totalArtworks: 16,
  },
  {
    id: 'artist-6',
    name: 'Marcus Thorne',
    handle: '@marcusthorne_photo',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    coverUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    bio: 'Fine art photographer specializing in serene fog landscapes and mist.',
    story: 'Marcus travels coastal mountain ranges to capture atmospheric silence, mountain ridges, and reflective alpine lakes.',
    location: 'Vancouver, Canada',
    socialLinks: { instagram: 'https://instagram.com' },
    featuredArtworkIds: ['art-14', 'art-15'],
    totalArtworks: 22,
  },
];

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: 'art-1',
    title: 'Morning Eucalyptus & Sun',
    artistId: 'artist-1',
    artistName: 'Elena Rostova',
    artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    description: 'Soft sage green eucalyptus leaves bathed in gentle early dawn sunlight. Calm and grounding.',
    medium: 'Oil on Linen',
    year: '2025',
    style: 'Botanical Realism',
    subject: 'Flora',
    colorPalette: ['#6B8A7A', '#EBE5D8', '#C48B47'],
    dimensions: '24" x 36"',
    tags: ['botanical', 'calm', 'sage', 'nature', 'plants'],
    supportedProductIds: ['prod-1', 'prod-2', 'prod-3', 'prod-4', 'prod-5', 'prod-7'],
    isFeatured: true,
    likesCount: 342,
    storySnippet: 'Painted during quiet autumn mornings in Elena’s greenhouse garden.',
  },
  {
    id: 'art-2',
    title: 'Golden Horizon No. 4',
    artistId: 'artist-3',
    artistName: 'Amara Vance',
    artistAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    description: 'Vibrant golden hour hues blended with terracotta layers and delicate metallic leaf detail.',
    medium: 'Acrylic & Gold Leaf',
    year: '2026',
    style: 'Abstract Expressionism',
    subject: 'Horizon',
    colorPalette: ['#D49B57', '#C86D51', '#141414'],
    dimensions: '30" x 40"',
    tags: ['abstract', 'gold', 'warm', 'anniversary', 'luxury'],
    supportedProductIds: ['prod-1', 'prod-2', 'prod-3', 'prod-6', 'prod-8'],
    isFeatured: true,
    likesCount: 512,
    storySnippet: 'A tribute to enduring warmth and golden memories.',
  },
  {
    id: 'art-3',
    title: 'Kyoto Mist & Bamboo',
    artistId: 'artist-2',
    artistName: 'Kenji Takahashi',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=800&q=80',
    description: 'Delicate charcoal ink wash depicting gentle bamboo stalks shrouded in morning mist.',
    medium: 'Sumi-e Ink on Washe Paper',
    year: '2025',
    style: 'Japanese Ink Wash',
    subject: 'Bamboo Forest',
    colorPalette: ['#1C1A18', '#8C8983', '#FAF8F5'],
    dimensions: '18" x 24"',
    tags: ['ink', 'minimalist', 'zen', 'calm', 'black and white'],
    supportedProductIds: ['prod-1', 'prod-2', 'prod-3', 'prod-5', 'prod-7'],
    isFeatured: true,
    likesCount: 289,
    storySnippet: 'Sketched during a misty walk in Arashiyama forest.',
  },
  {
    id: 'art-4',
    title: 'Terracotta Earth & Curves',
    artistId: 'artist-4',
    artistName: 'Mateo Morales',
    artistAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
    description: 'Warm ceramic arches and organic clay contours celebrating artisanal simplicity.',
    medium: 'Mixed Media & Clay Pigments',
    year: '2025',
    style: 'Modern Organic',
    subject: 'Architecture',
    colorPalette: ['#C86D51', '#EBE5D8', '#7A4D3B'],
    dimensions: '20" x 20"',
    tags: ['terracotta', 'organic', 'warm', 'modern', 'housewarming'],
    supportedProductIds: ['prod-1', 'prod-2', 'prod-4', 'prod-8'],
    isFeatured: false,
    likesCount: 198,
  },
  {
    id: 'art-5',
    title: 'Waterlilies at Dusk',
    artistId: 'artist-5',
    artistName: 'Sophie Laurent',
    artistAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?auto=format&fit=crop&w=800&q=80',
    description: 'Luminous pastel waterlilies in twilight violet, soft sage, and warm rose water reflection.',
    medium: 'Soft Pastel on Paper',
    year: '2025',
    style: 'Contemporary Impressionism',
    subject: 'Garden Pond',
    colorPalette: ['#5E6B82', '#A38DA6', '#6B8A7A'],
    dimensions: '24" x 30"',
    tags: ['impressionism', 'waterlilies', 'soft', 'violet', 'pastel'],
    supportedProductIds: ['prod-1', 'prod-2', 'prod-3', 'prod-6'],
    isFeatured: true,
    likesCount: 420,
  },
  {
    id: 'art-6',
    title: 'Alpine Lake Silence',
    artistId: 'artist-6',
    artistName: 'Marcus Thorne',
    artistAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    description: 'Mirror-like alpine lake reflecting towering pine ridges under moody morning clouds.',
    medium: 'Archival Fine Art Photography',
    year: '2026',
    style: 'Fine Art Landscape Photography',
    subject: 'Mountains & Lake',
    colorPalette: ['#2F3E46', '#52796F', '#CAD2C5'],
    dimensions: '30" x 45"',
    tags: ['photography', 'mountains', 'lake', 'serene', 'nature'],
    supportedProductIds: ['prod-1', 'prod-3', 'prod-5', 'prod-7'],
    isFeatured: false,
    likesCount: 310,
  },
  {
    id: 'art-7',
    title: 'Warm Citrus & Olive Blossom',
    artistId: 'artist-1',
    artistName: 'Elena Rostova',
    artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=800&q=80',
    description: 'Bright citrus fruits nestled amidst delicate olive blossoms and sunlit ceramic bowls.',
    medium: 'Oil on Wood Panel',
    year: '2025',
    style: 'Botanical Still Life',
    subject: 'Citrus & Flora',
    colorPalette: ['#E9A048', '#6B8A7A', '#F7EFE6'],
    dimensions: '16" x 20"',
    tags: ['citrus', 'kitchen', 'warm', 'olive', 'bright'],
    supportedProductIds: ['prod-2', 'prod-4', 'prod-8'],
    isFeatured: false,
    likesCount: 175,
  },
  {
    id: 'art-8',
    title: 'Architectural Shadow & Arch',
    artistId: 'artist-2',
    artistName: 'Kenji Takahashi',
    artistAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    description: 'Clean architectural shadows cast upon warm sandy limestone walls.',
    medium: 'Digital Vector & Ink',
    year: '2026',
    style: 'Architectural Minimal',
    subject: 'Shadow & Light',
    colorPalette: ['#D6C7B2', '#33302B', '#A89985'],
    dimensions: '20" x 30"',
    tags: ['architecture', 'shadow', 'minimal', 'modern'],
    supportedProductIds: ['prod-1', 'prod-3', 'prod-5'],
    isFeatured: false,
    likesCount: 224,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Gallery Canvas Print',
    category: 'wall-art',
    subcategory: 'Stretched Canvas',
    mockupImageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 88,
    availableColors: [
      { name: 'Natural Pine Frame', hex: '#D2B48C' },
      { name: 'Gallery Black Frame', hex: '#1C1A18' },
      { name: 'Museum White Frame', hex: '#FFFFFF' },
    ],
    description: 'Heavyweight museum-grade 100% cotton canvas with solid hardwood stretcher bars and archival pigment inks.',
    dimensions: '16" x 24" / 24" x 36"',
    material: '100% Cotton Canvas & Sustainable Wood',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'rotate', 'color'],
    aspectRatio: 1.5,
    printAreaRatio: { x: 0.05, y: 0.05, width: 0.9, height: 0.9 },
  },
  {
    id: 'prod-2',
    title: 'Artisan Ceramic Mug',
    category: 'drinkware',
    subcategory: 'Ceramic Drinkware',
    mockupImageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 34,
    availableColors: [
      { name: 'Warm Off-White', hex: '#FAF8F5', previewOverlayHex: '#FAF8F5' },
      { name: 'Matte Charcoal Black', hex: '#242424', previewOverlayHex: '#242424' },
      { name: 'Terracotta Red', hex: '#B85B43', previewOverlayHex: '#B85B43' },
      { name: 'Sage Green', hex: '#587462', previewOverlayHex: '#587462' },
    ],
    description: '14 oz handcrafted ceramic mug with ergonomic handle and glossy microwave-safe glaze.',
    dimensions: '14 oz / 415 ml',
    material: 'High-fire Stoneware Ceramic',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'rotate', 'text', 'color'],
    aspectRatio: 1.0,
    printAreaRatio: { x: 0.15, y: 0.15, width: 0.7, height: 0.7 },
  },
  {
    id: 'prod-3',
    title: 'Fine Art Framed Print',
    category: 'wall-art',
    subcategory: 'Framed Paper',
    mockupImageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 96,
    availableColors: [
      { name: 'Solid Oak Frame', hex: '#C6A17B' },
      { name: 'Matte Black Aluminum', hex: '#1C1A18' },
      { name: 'Satin White Frame', hex: '#F5F5F0' },
    ],
    description: '300 gsm acid-free rag paper framed behind UV-protective museum acrylic glass.',
    dimensions: '18" x 24"',
    material: 'Cotton Rag Paper & UV Glass',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'color'],
    aspectRatio: 1.33,
    printAreaRatio: { x: 0.1, y: 0.1, width: 0.8, height: 0.8 },
  },
  {
    id: 'prod-4',
    title: 'Organic Cotton Tote Bag',
    category: 'apparel',
    subcategory: 'Bags & Totes',
    mockupImageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 42,
    availableColors: [
      { name: 'Natural Unbleached Cotton', hex: '#EDE6D8' },
      { name: 'Midnight Navy', hex: '#1B263B' },
      { name: 'Olive Sage', hex: '#4A5D4E' },
    ],
    description: 'Heavy-duty 12 oz organic canvas tote with reinforced shoulder straps and internal zip pocket.',
    dimensions: '15" x 16" x 4"',
    material: '100% Organic Canvas Cotton',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'rotate', 'text', 'color'],
    aspectRatio: 1.0,
    printAreaRatio: { x: 0.1, y: 0.15, width: 0.8, height: 0.7 },
  },
  {
    id: 'prod-5',
    title: 'Minimalist Phone Case',
    category: 'accessories',
    subcategory: 'Tech Accessories',
    mockupImageUrl: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 38,
    availableColors: [
      { name: 'Clear Matte', hex: '#EAEAEA' },
      { name: 'Soft Obsidian', hex: '#1F1F1F' },
      { name: 'Sand Beige', hex: '#DCD4C4' },
    ],
    description: 'Slim impact-resistant polycarbonate case with raised camera bevel and MagSafe compatibility.',
    dimensions: 'iPhone & Galaxy Models',
    material: 'Polycarbonate & TPU Cushion',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'rotate', 'color'],
    aspectRatio: 0.5,
    printAreaRatio: { x: 0.05, y: 0.05, width: 0.9, height: 0.9 },
  },
  {
    id: 'prod-6',
    title: '100% Mulberry Silk Scarf',
    category: 'accessories',
    subcategory: 'Wearables',
    mockupImageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 110,
    availableColors: [
      { name: 'Pearl Ivory', hex: '#FAF5EF' },
      { name: 'Champagne Gold', hex: '#E8D4B8' },
    ],
    description: 'Luminous 16 momme Mulberry silk square scarf with hand-rolled hems and vibrant art printing.',
    dimensions: '35" x 35" / 90 cm x 90 cm',
    material: '100% Mulberry Silk',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'color'],
    aspectRatio: 1.0,
    printAreaRatio: { x: 0.0, y: 0.0, width: 1.0, height: 1.0 },
  },
  {
    id: 'prod-7',
    title: 'Insulated Travel Tumbler',
    category: 'drinkware',
    subcategory: 'Tumblers',
    mockupImageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 48,
    availableColors: [
      { name: 'Brush Stainless', hex: '#D8D8D8' },
      { name: 'Matte Cream', hex: '#F7F3EC' },
      { name: 'Forest Green', hex: '#2C4A3E' },
    ],
    description: '20 oz double-wall vacuum insulated stainless steel tumbler keeping drinks cold for 24 hours.',
    dimensions: '20 oz / 600 ml',
    material: '18/8 Food Grade Stainless Steel',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'text', 'color'],
    aspectRatio: 0.6,
    printAreaRatio: { x: 0.1, y: 0.2, width: 0.8, height: 0.6 },
  },
  {
    id: 'prod-8',
    title: 'Artisan Ceramic Plate',
    category: 'home-decor',
    subcategory: 'Tabletop',
    mockupImageUrl: 'https://images.unsplash.com/photo-1536939459926-301728717817?auto=format&fit=crop&w=800&q=80',
    basePriceCad: 62,
    availableColors: [
      { name: 'Glazed Cream', hex: '#F8F6F0' },
      { name: 'Raw Terracotta Edge', hex: '#C86D51' },
    ],
    description: 'Decorative stoneware plate crafted by traditional ceramicists for wall mounting or display.',
    dimensions: '10" Diameter',
    material: 'Glazed Stoneware',
    isCustomizable: true,
    supportedOperations: ['move', 'scale', 'rotate'],
    aspectRatio: 1.0,
    printAreaRatio: { x: 0.1, y: 0.1, width: 0.8, height: 0.8 },
  },
];

export const MOCK_OCCASIONS: GiftOccasion[] = [
  {
    id: 'occ-1',
    slug: 'anniversary',
    title: 'Anniversaries & Milestones',
    subtitle: 'Golden moments, lasting warmth, and artful memories',
    coverImageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    recommendedTag: 'gold & botanical',
  },
  {
    id: 'occ-2',
    slug: 'birthday',
    title: 'Thoughtful Birthdays',
    subtitle: 'Uniquely personalized art gifts tailored to their aesthetic',
    coverImageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    recommendedTag: 'artisan mug & print',
  },
  {
    id: 'occ-3',
    slug: 'housewarming',
    title: 'New Home & Warm Spaces',
    subtitle: 'Statement wall art and calming ceramic home touches',
    coverImageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    recommendedTag: 'gallery canvas & plate',
  },
  {
    id: 'occ-4',
    slug: 'wedding',
    title: 'Weddings & Celebrations',
    subtitle: 'Heirloom quality canvas prints and custom silk keepsakes',
    coverImageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80',
    recommendedTag: 'silk scarf & fine print',
  },
  {
    id: 'occ-5',
    slug: 'valentines',
    title: 'Love & Romance',
    subtitle: 'Poetic botanical flora and cozy morning coffee sets',
    coverImageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    recommendedTag: 'eucalyptus & rose',
  },
  {
    id: 'occ-6',
    slug: 'thank-you',
    title: 'Gratitude & Appreciation',
    subtitle: 'Elegant everyday items featuring calming minimalist art',
    coverImageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    recommendedTag: 'organic tote & mug',
  },
];

export const MOCK_GIFT_CONCEPTS: GiftConcept[] = [
  {
    id: 'concept-1',
    title: 'Botanical Sun Anniversary Mug',
    tagline: 'Warm morning coffee surrounded by serene botanical leaves.',
    occasion: 'anniversary',
    recipient: 'partner',
    artworkId: 'art-1',
    productId: 'prod-2',
    mockupPreviewUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    suggestedText: 'Forever & Always • 2026',
    estimatedPriceCad: 34,
    reason: 'Combines Elena’s calm botanical flora with an everyday morning ritual.',
  },
  {
    id: 'concept-2',
    title: 'Golden Horizon Stretched Canvas',
    tagline: 'A luminous golden statement piece for living rooms.',
    occasion: 'anniversary',
    recipient: 'partner',
    artworkId: 'art-2',
    productId: 'prod-1',
    mockupPreviewUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    suggestedText: 'M & E',
    estimatedPriceCad: 88,
    reason: 'Rich gold leaf tones bring warmth and timeless elegance to shared spaces.',
  },
  {
    id: 'concept-3',
    title: 'Kyoto Zen Ink Framed Print',
    tagline: 'Peaceful Japanese sumi-e ink art in an oak frame.',
    occasion: 'housewarming',
    recipient: 'art-collectors',
    artworkId: 'art-3',
    productId: 'prod-3',
    mockupPreviewUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    estimatedPriceCad: 96,
    reason: 'Perfect neutral artwork for entryways or minimalist study spaces.',
  },
  {
    id: 'concept-4',
    title: 'Terracotta Clay Ceramic Plate',
    tagline: 'Warm organic lines for dining display and art collection.',
    occasion: 'housewarming',
    recipient: 'friends',
    artworkId: 'art-4',
    productId: 'prod-8',
    mockupPreviewUrl: 'https://images.unsplash.com/photo-1536939459926-301728717817?auto=format&fit=crop&w=800&q=80',
    estimatedPriceCad: 62,
    reason: 'Handcrafted stoneware feel with artisanal terracotta glaze.',
  },
  {
    id: 'concept-5',
    title: 'Waterlilies Silk Scarf',
    tagline: 'Luminous 100% Mulberry silk scarf with impressionist art.',
    occasion: 'birthday',
    recipient: 'parents',
    artworkId: 'art-5',
    productId: 'prod-6',
    mockupPreviewUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80',
    estimatedPriceCad: 110,
    reason: 'Ethereal pastel hues printed on soft, luxurious Mulberry silk.',
  },
];
